version: '3.2'

services: 
  tomcat-1:
    image: tomcat
    build: .
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./example-1/example.war
        target: /usr/local/tomcat/webapps/example.war



  tomcat-2:
    image: tomcat
    build: .
    ports:
      - "8081:8080"

    volumes:
      - type: bind
        source: ./example-2/example.war
        target: /usr/local/tomcat/webapps/example.war


  tomcat-3:
    image: tomcat
    build: .
    ports:
      - "8082:8082"
    volumes:
        source: ./example-3/example.war
        target: /usr/local/tomcat/webapps/example.war
  postgres: 
    image: postgres:9.6
    environment: 
      - POSTGRES_PASSWORD=mypass
      - POSTGRES_DB=tomcat_example
      - POSTGRES_USER=tomcat_example
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
  example-3:
